/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RequisitionsIndexRouteImport } from './routes/requisitions.index'
import { Route as RequisitionsIdRouteImport } from './routes/requisitions.$id'
import { Route as RequisitionsNewRouteImport } from './routes/requisitions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsIndexRoute = RequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsIdRoute = RequisitionsIdRouteImport.update({
  id: '/requisitions/$id',
  path: '/requisitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsNewRoute = RequisitionsNewRouteImport.update({
  id: '/requisitions/new',
  path: '/requisitions/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/requisitions/new': typeof RequisitionsNewRoute
  '/requisitions/': typeof RequisitionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/requisitions/new': typeof RequisitionsNewRoute
  '/requisitions': typeof RequisitionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/requisitions/new': typeof RequisitionsNewRoute
  '/requisitions/': typeof RequisitionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/queue'
    | '/requisitions/$id'
    | '/requisitions/new'
    | '/requisitions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/queue'
    | '/requisitions/$id'
    | '/requisitions/new'
    | '/requisitions'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/queue'
    | '/requisitions/$id'
    | '/requisitions/new'
    | '/requisitions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  QueueRoute: typeof QueueRoute
  RequisitionsIdRoute: typeof RequisitionsIdRoute
  RequisitionsNewRoute: typeof RequisitionsNewRoute
  RequisitionsIndexRoute: typeof RequisitionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/': {
      id: '/requisitions/'
      path: '/requisitions'
      fullPath: '/requisitions/'
      preLoaderRoute: typeof RequisitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/$id': {
      id: '/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/requisitions/$id'
      preLoaderRoute: typeof RequisitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/new': {
      id: '/requisitions/new'
      path: '/requisitions/new'
      fullPath: '/requisitions/new'
      preLoaderRoute: typeof RequisitionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  QueueRoute: QueueRoute,
  RequisitionsIdRoute: RequisitionsIdRoute,
  RequisitionsNewRoute: RequisitionsNewRoute,
  RequisitionsIndexRoute: RequisitionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
